name: Atlas Secrets Management
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup pipenv environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv --version
          pipenv install --dev
      - name: Run pre-commit checks
        run: |
          pipenv run pre-commit run --all-files
      - name: Fetch secrets from GitHub environment
        run: |
          echo "FOO=${FOO}"
          echo "GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}"
        env:
          FOO: ${{ secrets.FOO }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Decrypt file secrets
        uses: ./.github/actions/decrypt-secret
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          secret-file: ./dev.env
      - name: Use secrets from previous step
        run: |
          echo "HAZ=${HAZ}"
          echo "BAZ=${BAZ}"
