name: Atlas Secrets Management
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup pipenv environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv --version
          pipenv install --dev
      - name: Run pre-commit checks
        run: |
          pipenv run pre-commit run --all-files
      - name: Ensure GitHub environment secrets are obfuscated
        run: |
          echo "FOO=${FOO}"
          echo "BAR=${BAR}"
          echo "GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}"
        env:
          FOO: ${{ secrets.FOO }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Decrypt file secrets
        uses: ./.github/actions/decrypt-secret
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          secret-file: ./dev.env
      - name: Ensure file secrets are obfuscated
        run: |
          echo "HAZ=${HAZ}"
          echo "BAZ=${BAZ}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Get secrets by name
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            exampleSecretName
            dev/foo
      - name: Ensure fetched secrets from SM are obfuscated
        run: |
          echo "EXAMPLESECRETNAME=${EXAMPLESECRETNAME}"
          echo "DEV_FOO=${DEV_FOO}"
